'use strict';

define({
    ACTION_CANCELED: 'Action is canceled.',
    ACTUAL_EXPECTED: 'Actual (left) - Expected (right)',
    ADDITIONAL_FLAGS: 'Additional Flags',
    ADDITIONAL_FLAGS_PLACEHOLDER: 'e.g. --bail for mocha, --require for node',
    ADD_TO_GULP_RUNNER: 'Add to gulp runner',
    ADD_TO_MOCHA_RUNNER: 'Add to Mocha runner',
    ADD_TO_NODEJS_RUNNER: 'Add to Node.js runner',
    ADD_TO_NPM_RUNNER: 'Add to NPM runner',
    AUTOSCROLL_IN_TERMINAL: 'Autoscroll in terminal',
    BUILT_IN_LIB: 'Built-in Node.js library',
    CANCEL: 'Cancel',
    CHOOSE_TARGET: 'Choose target...',
    CHOOSE_WORKINGS_DIRECTORY: 'Choose working directory...',
    CLICK_TO_CHANGE_RUNNER: 'Click to change runner',
    CLICK_TO_CHANGE_SCRIPT: 'Click to change script',
    CLICK_TO_COPY_VALUE: 'Click to copy value',
    CLICK_TO_OPEN: 'Click to open',
    CLOSE: 'Close',
    CLOSE_CURRENT_TAB: 'Close current tab',
    COLLAPSE_ALL: 'Collapse All',
    CREATE_NEW_TAB: 'Create new tab',
    CURRENT_DIRECTORY: 'Current directory',
    CWD: 'CWD',
    DEBUG: 'Debug',
    DEBUGGER_CLEAR_CONSOLE: 'Clear console',
    DEBUGGER_CONNECTED: 'Debugger: connected.',
    DEBUGGER_CONNECT_STATUS: 'Connect status',
    DEBUGGER_CONSOLE: 'Console',
    DEBUGGER_CONTINUE: 'Continue',
    DEBUGGER_CONTINUE_ACTIVE_RUNNER: 'Debugger - continue (active runner)',
    DEBUGGER_FIRST_BREAK: 'Debugger: connected. Please set breakpoint and click "Continue" button on runner panel.',
    DEBUGGER_HELP: 'Help',
    DEBUGGER_JUMP_TO_BREAK: 'Jump to break',
    DEBUGGER_LOOKUP_DEPTH: 'Debugger lookup depth',
    DEBUGGER_SCRIPTS: 'Scripts',
    DEBUGGER_STEP_IN: 'Step in',
    DEBUGGER_STEP_OUT: 'Step out',
    DEBUGGER_STEP_OVER_ACTIVE_RUNNER: 'Debugger - step over (active runner)',
    DEBUGGER_STEP_OVER_TO_NEXT_FUNCTION: 'Step over to next function',
    DEBUG_ACTIVE_RUNNER: 'Debug (active runner)',
    DIFF_ACTUAL: 'Actual',
    DIFF_EXPECTED: 'Expected',
    DIFF_TITLE: 'Actual/Expected difference',
    DIRECTORY: 'Directory',
    EXPAND_ALL: 'Expand All',
    FILE: 'File',
    FLAGS_FOR_V8: 'Flags for v8',
    FLAGS_FOR_V8_PLACEHOLDER: 'example: --use_strict --harmony',
    GLOBAL_ADDITIONAL_FLAGS: 'Global Additional Flags',
    GLOBAL_ADDITIONAL_FLAGS_PLACEHOLDER: 'e.g. --bail for mocha, --require for node',
    HIDE_DIFFERENCE: 'Hide difference',
    INSTALL_DEPENDENCIES: 'Install dependencies...',
    INSTALLATION_FAILED: 'Installation failed',
    INSTALLATION_FAILED_MESSAGE: 'The installation is not finished. Please go to the extension folder in your terminal and run "npm install" command.',
    INSTALLATION_FINISHED: 'Installation finished',
    JUMP_TO_REQUIRE: 'Jump to Require',
    NAME: 'Name',
    NEW_TAB: 'New Tab',
    OPEN_SETTINGS: 'Open settings',
    PACKAGE: 'Package',
    PARENT_DIRECTORY: 'Parent directory',
    PATH_TO_MOCHA_BINARY: 'Path to Mocha binary',
    PATH_TO_MOCHA_BINARY_PLACEHOLDER: 'leave empty for global mocha command',
    PATH_TO_GULP_BINARY: 'Path to Gulp binary',
    PATH_TO_GULP_BINARY_PLACEHOLDER: 'leave empty for global gulp command',
    PATH_TO_NODE_BINARY: 'Path to Node binary',
    PATH_TO_NODE_BINARY_PLACEHOLDER: 'leave empty for global node command',
    PATH_TO_NPM_BINARY: 'Path to npm binary',
    PATH_TO_NPM_BINARY_PLACEHOLDER: 'leave empty for global npm command',
    REMOVE_BREAKPOINTS_ON_DISCONNECT: 'Remove breakpoints on disconnect',
    RINNERS_LIMITATION: 'Limitations: You can start only 5 runners.',
    RUN: 'Run',
    RUNNER_SETTINGS: 'Runner settings',
    SAVE: 'Save',
    SEARCH: 'Search',
    SETTINGS: 'Settings...',
    SHOW_OR_HIDE_RUNNER: 'Show/Hide runner',
    SHOW_DIFFERENCE: 'Show difference',
    START_ACTIVE_RUNNER: 'Start (active runner)',
    START_CURRENT_MOCHA_FILE: 'Start (current Mocha file)',
    START_CURRENT_NODEJS_FILE: 'Start (current NodeJS file)',
    START_CURRENT_NODEJS_PROJECT: 'Start (current NodeJS project)',
    STOP: 'Stop',
    STOP_ACTIVE_RUNNER: 'Stop (active runner)',
    TARGET: 'Target',
    TARGET_EMPTY: 'The target in your run configuration is empty.',
    TESTS: 'Tests',
    TOGGLE_DEBUGGER: 'Toggle debugger',
    TOGGLE_MOCHA: 'Toggle mocha view'
});
