'use strict';

define({
    ADDITIONAL_FLAGS: 'Дополнительные Флаги',
    ADDITIONAL_FLAGS_PLACEHOLDER: 'например --bail для mocha, --require для node',
    ADD_TO_GULP_RUNNER: 'Добавить gulp runner',
    ADD_TO_MOCHA_RUNNER: 'Добавить Mocha runner',
    ADD_TO_NODEJS_RUNNER: 'Добавить Node.js runner',
    ADD_TO_NPM_RUNNER: 'Добавить NPM runner',
    AUTOSCROLL_IN_TERMINAL: 'Автопрокрутка в терминале',
    CANCEL: 'Отменить',
    CHOOSE_TARGET: 'Выбрать цель...',
    CHOOSE_WORKINGS_DIRECTORY: 'Выбрать рабочий каталог...',
    CLICK_TO_CHANGE_RUNNER: 'Нажмите, чтобы изменить runner',
    CLICK_TO_CHANGE_SCRIPT: 'Нажмите, чтобы изменить script',
    CLOSE: 'Закрыть',
    CLOSE_CURRENT_TAB: 'Закрыть текущую вкладку',
    COLLAPSE_ALL: 'Свернуть все',
    CREATE_NEW_TAB: 'Создать новую вкладку',
    CWD: 'CWD',
    DEBUG: 'Отладка',
    DEBUGGER_CONTINUE_ACTIVE_RUNNER: 'Отладчик - продолжить (активный runner)',
    DEBUGGER_LOOKUP_DEPTH: 'Глубина поиска отладчика',
    DEBUGGER_STEP_OVER_ACTIVE_RUNNER: 'Отладки - шаг с обходом (активный runner)',
    DEBUG_ACTIVE_RUNNER: 'Отладка (активный runner)',
    EXPAND_ALL: 'Развернуть все',
    FLAGS_FOR_V8: 'Флаги для V8',
    FLAGS_FOR_V8_PLACEHOLDER: 'например: --use_strict --harmony',
    GLOBAL_ADDITIONAL_FLAGS: 'Дополнительные глобальные флаги',
    GLOBAL_ADDITIONAL_FLAGS_PLACEHOLDER: 'например --bail для mocha, --require для node',
    JUMP_TO_REQUIRE: 'Перейти к Require',
    NAME: 'Имя',
    NEW_TAB: 'Новая вкладка',
    OPEN_SETTINGS: 'Открыть настройки',
    PATH_TO_MOCHA_BINARY: 'Путь к Mocha',
    PATH_TO_MOCHA_BINARY_PLACEHOLDER: 'оставьте пустым для глобальной mocha команды',
    PATH_TO_NODE_BINARY: 'Путь к Node',
    PATH_TO_NODE_BINARY_PLACEHOLDER: 'оставьте пустым для глобальной node команды',
    PATH_TO_NPM_BINARY: 'Путь к Mocha',
    PATH_TO_NPM_BINARY_PLACEHOLDER: 'оставьте пустым для глобальной npm команды',
    REMOVE_BREAKPOINTS_ON_DISCONNECT: 'Удалить точки остановки при отключении',
    RINNERS_LIMITATION: 'Ограничения: Вы можете создать только 5 runner.',
    RUN: 'Старт',
    RUNNER_SETTINGS: 'Настройки',
    SAVE: 'Сохранить',
    SEARCH: 'Поиск',
    SETTINGS: 'Настройки...',
    SHOW_OR_HIDE_RUNNER: 'Показать/Спрятать runner',
    START_ACTIVE_RUNNER: 'Старт (активный runner)',
    START_CURRENT_MOCHA_FILE: 'Старт (текущий Mocha файл)',
    START_CURRENT_NODEJS_FILE: 'Старт (текущий NodeJS файл)',
    STOP: 'Стоп',
    STOP_ACTIVE_RUNNER: 'Стор (активный runner)',
    TARGET: 'Цель',
    TESTS: 'Тесты',
    TOGGLE_DEBUGGER: 'Переключить отладчик',
    TOGGLE_MOCHA: 'Переключить mocha панель'
});
