'use strict';

define({
    ACTION_CANCELED: 'Действие прервано.',
    ACTUAL_EXPECTED: 'Актуальное (слева) - Ожидаемое (справа)',
    ADDITIONAL_FLAGS: 'Дополнительные Флаги',
    ADDITIONAL_FLAGS_PLACEHOLDER: 'например --bail для mocha, --require для node',
    ADD_TO_GULP_RUNNER: 'Добавить gulp runner',
    ADD_TO_MOCHA_RUNNER: 'Добавить Mocha runner',
    ADD_TO_NODEJS_RUNNER: 'Добавить Node.js runner',
    ADD_TO_NPM_RUNNER: 'Добавить NPM runner',
    AUTOSCROLL_IN_TERMINAL: 'Автопрокрутка в терминале',
    BUILT_IN_LIB: 'Встроенная Node.js библиотека',
    CANCEL: 'Отменить',
    CHOOSE_TARGET: 'Выбрать цель...',
    CHOOSE_WORKINGS_DIRECTORY: 'Выбрать рабочий каталог...',
    CLICK_TO_CHANGE_RUNNER: 'Нажмите, чтобы изменить runner',
    CLICK_TO_CHANGE_SCRIPT: 'Нажмите, чтобы изменить script',
    CLICK_TO_COPY_VALUE: 'Нажмите, чтобы скопировать значение',
    CLICK_TO_OPEN: 'Нажмите, чтобы открыть',
    CLOSE: 'Закрыть',
    CLOSE_CURRENT_TAB: 'Закрыть текущую вкладку',
    COLLAPSE_ALL: 'Свернуть все',
    CREATE_NEW_TAB: 'Создать новую вкладку',
    CURRENT_DIRECTORY: 'Текущий каталог',
    CWD: 'CWD',
    DEBUG: 'Отладка',
    DEBUGGER_CLEAR_CONSOLE: 'Очистить консоль',
    DEBUGGER_CONNECTED: 'Отладка: подключено.',
    DEBUGGER_CONNECT_STATUS: 'Состояние подключения.',
    DEBUGGER_CONSOLE: 'Консоль',
    DEBUGGER_CONTINUE: 'Продолжить',
    DEBUGGER_CONTINUE_ACTIVE_RUNNER: 'Отладчик - продолжить (активный runner)',
    DEBUGGER_FIRST_BREAK: 'Отладка: подключено. Пожалуйста установите точку остановки и нажмите на кнопку "Продолжить".',
    DEBUGGER_HELP: 'Помощь',
    DEBUGGER_JUMP_TO_BREAK: 'Перейти к точке остановки',
    DEBUGGER_LOOKUP_DEPTH: 'Глубина поиска отладчика',
    DEBUGGER_SCRIPTS: 'Скрипты',
    DEBUGGER_STEP_IN: 'Шаг внутрь',
    DEBUGGER_STEP_OUT: 'Шаг наружу',
    DEBUGGER_STEP_OVER_ACTIVE_RUNNER: 'Отладки - шаг с обходом (активный runner)',
    DEBUGGER_STEP_OVER_TO_NEXT_FUNCTION: 'Шаг к следующей функции',
    DEBUG_ACTIVE_RUNNER: 'Отладка (активный runner)',
    DIFF_ACTUAL: 'Актуальное',
    DIFF_EXPECTED: 'Ожидаемое',
    DIFF_TITLE: 'Актуальная/Ожидаемая разница',
    DIRECTORY: 'Папка',
    EXPAND_ALL: 'Развернуть все',
    FILE: 'Файл',
    FLAGS_FOR_V8: 'Флаги для V8',
    FLAGS_FOR_V8_PLACEHOLDER: 'например: --use_strict --harmony',
    GLOBAL_ADDITIONAL_FLAGS: 'Дополнительные глобальные флаги',
    GLOBAL_ADDITIONAL_FLAGS_PLACEHOLDER: 'например --bail для mocha, --require для node',
    HIDE_DIFFERENCE: 'Скрыть разницу',
    INSTALL_DEPENDENCIES: 'Установка зависимостей...',
    INSTALLATION_FAILED: 'Уставновка прервана',
    INSTALLATION_FAILED_MESSAGE: 'Установка не заверщена. Пожалуйста проследуйте в папку аддона и выполните "npm install" команду.',
    INSTALLATION_FINISHED: 'Установка завершена',
    JUMP_TO_REQUIRE: 'Перейти к Require',
    NAME: 'Имя',
    NEW_TAB: 'Новая вкладка',
    OPEN_SETTINGS: 'Открыть настройки',
    PACKAGE: 'Пакет',
    PARENT_DIRECTORY: 'Родительский каталог',
    PATH_TO_MOCHA_BINARY: 'Путь к Mocha',
    PATH_TO_MOCHA_BINARY_PLACEHOLDER: 'оставьте пустым для глобальной mocha команды',
    PATH_TO_GULP_BINARY: 'Путь к Gulp',
    PATH_TO_GULP_BINARY_PLACEHOLDER: 'оставьте пустым для глобальной gulp команды',
    PATH_TO_NODE_BINARY: 'Путь к Node',
    PATH_TO_NODE_BINARY_PLACEHOLDER: 'оставьте пустым для глобальной node команды',
    PATH_TO_NPM_BINARY: 'Путь к Mocha',
    PATH_TO_NPM_BINARY_PLACEHOLDER: 'оставьте пустым для глобальной npm команды',
    REMOVE_BREAKPOINTS_ON_DISCONNECT: 'Удалить точки остановки при отключении',
    RINNERS_LIMITATION: 'Ограничения: Вы можете создать только 5 runner.',
    RUN: 'Старт',
    RUNNER_SETTINGS: 'Настройки',
    SAVE: 'Сохранить',
    SEARCH: 'Поиск',
    SETTINGS: 'Настройки...',
    SHOW_OR_HIDE_RUNNER: 'Показать/Спрятать runner',
    SHOW_DIFFERENCE: 'Показать разницу',
    START_ACTIVE_RUNNER: 'Старт (активный runner)',
    START_CURRENT_MOCHA_FILE: 'Старт (текущий Mocha файл)',
    START_CURRENT_NODEJS_FILE: 'Старт (текущий NodeJS файл)',
    START_CURRENT_NODEJS_PROJECT: 'Старт (текущий NodeJS проект)',
    STOP: 'Стоп',
    STOP_ACTIVE_RUNNER: 'Стор (активный runner)',
    TARGET: 'Цель',
    TARGET_EMPTY: 'Не задана цель в настройке.',
    TESTS: 'Тесты',
    TOGGLE_DEBUGGER: 'Переключить отладчик',
    TOGGLE_MOCHA: 'Переключить mocha панель'
});
