'use strict';

define({
    ADDITIONAL_FLAGS: 'Zusätzliche Flags',
    ADDITIONAL_FLAGS_PLACEHOLDER: 'z.B. --bail für mocha, --require für node',
    ADD_TO_GULP_RUNNER: 'Hinzufügen gulp runner',
    ADD_TO_MOCHA_RUNNER: 'Hinzufügen Mocha runner',
    ADD_TO_NODEJS_RUNNER: 'Hinzufügen Node.js runner',
    ADD_TO_NPM_RUNNER: 'Hinzufügen NPM runner',
    AUTOSCROLL_IN_TERMINAL: 'Autoscroll im terminal',
    CANCEL: 'Abbrechen',
    CHOOSE_TARGET: 'Das Ziel auswählen...',
    CHOOSE_WORKINGS_DIRECTORY: 'Arbeitsverzeichnis auswählen...',
    CLICK_TO_CHANGE_RUNNER: 'Runner auswählen',
    CLICK_TO_CHANGE_SCRIPT: 'Script auswählen',
    CLOSE: 'Schließen',
    COLLAPSE_ALL: 'Alle ausblenden',
    CREATE_NEW_TAB: 'Neue pannel erstellen',
    CWD: 'CWD',
    DEBUG: 'Debug',
    DEBUGGER_CONTINUE_ACTIVE_RUNNER: 'Debugger - weiterhin (aktive runner)',
    DEBUGGER_LOOKUP_DEPTH: 'Debugger-lookup-Tiefe',
    DEBUGGER_STEP_OVER_ACTIVE_RUNNER: 'Debugger - schritt über (aktive runner)',
    DEBUG_ACTIVE_RUNNER: 'Debug (aktive runner)',
    EXPAND_ALL: 'Alle Einblenden',
    FLAGS_FOR_V8: 'Flags für v8',
    FLAGS_FOR_V8_PLACEHOLDER: 'z.B. --use_strict --harmony',
    GLOBAL_ADDITIONAL_FLAGS: 'Globale Weitere Flags',
    GLOBAL_ADDITIONAL_FLAGS_PLACEHOLDER: 'z.B. --bail für mocha, --require für node',
    JUMP_TO_REQUIRE: 'Springen zu Require',
    NAME: 'Name',
    NEW_TAB: 'Neue pannel',
    OPEN_SETTINGS: 'Einstellungen öffnen',
    PATH_TO_MOCHA_BINARY: 'Pfad zum Mocha binary',
    PATH_TO_MOCHA_BINARY_PLACEHOLDER: 'leer lassen für die globale mocha Befehl',
    PATH_TO_NODE_BINARY: 'Pfad zum Node binary',
    PATH_TO_NODE_BINARY_PLACEHOLDER: 'leer lassen für die globale node Befehl',
    PATH_TO_NPM_BINARY: 'Pfad zum npm binary',
    PATH_TO_NPM_BINARY_PLACEHOLDER: 'leer lassen für die globale npm Befehl',
    REMOVE_BREAKPOINTS_ON_DISCONNECT: 'Entfernen von Haltepunkten auf disconnect',
    RINNERS_LIMITATION: 'Einschränkungen: Sie können nur fünf runners starten.',
    RUN: 'Start',
    RUNNER_SETTINGS: 'Runner Einstellungen',
    SAVE: 'Speichern',
    SEARCH: 'Suche',
    SETTINGS: 'Einstellungen...',
    SHOW_OR_HIDE_RUNNER: 'Ein-/Ausblenden runner',
    START_ACTIVE_RUNNER: 'Start (aktive runner)',
    START_CURRENT_MOCHA_FILE: 'Start (aktuelle Mocha Datei)',
    START_CURRENT_NODEJS_FILE: 'Start (aktuelle NodeJS Datei)',
    STOP: 'Stop',
    STOP_ACTIVE_RUNNER: 'Stop (aktueller runner)',
    TARGET: 'Ziel',
    TESTS: 'Tests',
    TOGGLE_DEBUGGER: 'Toggle debugger',
    TOGGLE_MOCHA: 'Toggle mocha view'
});
