'use strict';

define({
    ACTUAL_EXPECTED: 'Aktueller (Links) - Erwarteter (rechts)',
    ADDITIONAL_FLAGS: 'Zusätzliche Flags',
    ADDITIONAL_FLAGS_PLACEHOLDER: 'z.B. --bail für mocha, --require für node',
    ADD_TO_GULP_RUNNER: 'Hinzufügen gulp runner',
    ADD_TO_MOCHA_RUNNER: 'Hinzufügen Mocha runner',
    ADD_TO_NODEJS_RUNNER: 'Hinzufügen Node.js runner',
    ADD_TO_NPM_RUNNER: 'Hinzufügen NPM runner',
    AUTOSCROLL_IN_TERMINAL: 'Autoscroll im terminal',
    BUILT_IN_LIB: 'Built-in Node.js Bibliothek',
    CANCEL: 'Abbrechen',
    CHOOSE_TARGET: 'Das Ziel auswählen...',
    CHOOSE_WORKINGS_DIRECTORY: 'Arbeitsverzeichnis auswählen...',
    CLICK_TO_CHANGE_RUNNER: 'Runner auswählen',
    CLICK_TO_CHANGE_SCRIPT: 'Script auswählen',
    CLICK_TO_COPY_VALUE: 'Der Wert kopieren',
    CLICK_TO_OPEN: 'Öffnen',
    CLOSE: 'Schließen',
    CLOSE_CURRENT_TAB: 'Aktive runner schließen',
    COLLAPSE_ALL: 'Alle ausblenden',
    CREATE_NEW_TAB: 'Neue pannel erstellen',
    CURRENT_DIRECTORY: 'Aktuelles Verzeichnis',
    CWD: 'CWD',
    DEBUG: 'Debug',
    DEBUGGER_CLEAR_CONSOLE: 'Konsole lehren',
    DEBUGGER_CONNECTED: 'Debugger: verbunden.',
    DEBUGGER_CONNECT_STATUS: 'Status des connection',
    DEBUGGER_CONSOLE: 'Konsole',
    DEBUGGER_CONTINUE: 'Weiter',
    DEBUGGER_CONTINUE_ACTIVE_RUNNER: 'Debugger - weiterhin (aktive runner)',
    DEBUGGER_FIRST_BREAK: 'Debugger: verbunden. Setzen Sie bitte ein Breakpoint und clicken Sie "Weiter".',
    DEBUGGER_HELP: 'Hilfe',
    DEBUGGER_JUMP_TO_BREAK: 'Zum Breakpoint springen',
    DEBUGGER_LOOKUP_DEPTH: 'Debugger-lookup-Tiefe',
    DEBUGGER_SCRIPTS: 'Scripts',
    DEBUGGER_STEP_IN: 'Eintreten',
    DEBUGGER_STEP_OUT: 'Heraustreten',
    DEBUGGER_STEP_OVER_ACTIVE_RUNNER: 'Debugger - schritt über (aktive runner)',
    DEBUGGER_STEP_OVER_TO_NEXT_FUNCTION: 'Schritt über zur nächsten Funktion',
    DEBUG_ACTIVE_RUNNER: 'Debug (aktive runner)',
    DIFF_ACTUAL: 'Aktueller',
    DIFF_EXPECTED: 'Erwarteter',
    DIFF_TITLE: 'Aktueller/Erwarteter Differenz',
    DIRECTORY: 'Verzeichnis',
    EXPAND_ALL: 'Alle Einblenden',
    FILE: 'Datei',
    FLAGS_FOR_V8: 'Flags für v8',
    FLAGS_FOR_V8_PLACEHOLDER: 'z.B. --use_strict --harmony',
    GLOBAL_ADDITIONAL_FLAGS: 'Globale Weitere Flags',
    GLOBAL_ADDITIONAL_FLAGS_PLACEHOLDER: 'z.B. --bail für mocha, --require für node',
    HIDE_DIFFERENCE: 'Differenz ausblenden',
    INSTALL_DEPENDENCIES: 'Abhängigkeiten installieren...',
    INSTALLATION_FINISHED: 'Installation ist abgeschlossen',
    JUMP_TO_REQUIRE: 'Springen zu Require',
    NAME: 'Name',
    NEW_TAB: 'Neue pannel',
    OPEN_SETTINGS: 'Einstellungen öffnen',
    PACKAGE: 'Package',
    PARENT_DIRECTORY: 'Übergeordnetes Verzeichnis',
    PATH_TO_MOCHA_BINARY: 'Pfad zum Mocha binary',
    PATH_TO_MOCHA_BINARY_PLACEHOLDER: 'leer lassen für die globale mocha Befehl',
    PATH_TO_NODE_BINARY: 'Pfad zum Node binary',
    PATH_TO_NODE_BINARY_PLACEHOLDER: 'leer lassen für die globale node Befehl',
    PATH_TO_NPM_BINARY: 'Pfad zum npm binary',
    PATH_TO_NPM_BINARY_PLACEHOLDER: 'leer lassen für die globale npm Befehl',
    REMOVE_BREAKPOINTS_ON_DISCONNECT: 'Entfernen von Haltepunkten auf disconnect',
    RINNERS_LIMITATION: 'Einschränkungen: Sie können nur fünf runners starten.',
    RUN: 'Start',
    RUNNER_SETTINGS: 'Runner Einstellungen',
    SAVE: 'Speichern',
    SEARCH: 'Suche',
    SETTINGS: 'Einstellungen...',
    SHOW_OR_HIDE_RUNNER: 'Ein-/Ausblenden runner',
    SHOW_DIFFERENCE: 'Differenz einblenden',
    START_ACTIVE_RUNNER: 'Start (aktive runner)',
    START_CURRENT_MOCHA_FILE: 'Start (aktuelle Mocha Datei)',
    START_CURRENT_NODEJS_FILE: 'Start (aktuelle NodeJS Datei)',
    START_CURRENT_NODEJS_PROJECT: 'Start (aktuelle NodeJS Projekt)',
    STOP: 'Stop',
    STOP_ACTIVE_RUNNER: 'Stop (aktueller runner)',
    TARGET: 'Ziel',
    TESTS: 'Tests',
    TOGGLE_DEBUGGER: 'Toggle debugger',
    TOGGLE_MOCHA: 'Toggle mocha view'
});
