'use strict';

define({
    ACTION_CANCELED: 'Ação cancelada.',
    ACTUAL_EXPECTED: 'Atual (esqueda) - Esperado (direita)',
    ADDITIONAL_FLAGS: 'Flags adicionais',
    ADDITIONAL_FLAGS_PLACEHOLDER: 'ex. --bail para o mocha, --require para o node',
    ADD_TO_GULP_RUNNER: 'Adicionar ao executor do Gulp',
    ADD_TO_MOCHA_RUNNER: 'Adicionar ao executor do Mocha',
    ADD_TO_NODEJS_RUNNER: 'Adicionar ao executor do Node.js',
    ADD_TO_NPM_RUNNER: 'Adicionar ao executor do NPM',
    AUTOSCROLL_IN_TERMINAL: 'Autoscroll no terminal',
    BUILT_IN_LIB: 'Biblioteca Node.js interna',
    CANCEL: 'Cancelar',
    CHOOSE_TARGET: 'Escolha o alvo...',
    CHOOSE_WORKINGS_DIRECTORY: 'Escolha a pasta de trabalho...',
    CLICK_TO_CHANGE_RUNNER: 'Clique para mudar o executor',
    CLICK_TO_CHANGE_SCRIPT: 'Clique para mudar o script',
    CLICK_TO_COPY_VALUE: 'Clique para o copiar o valor',
    CLICK_TO_OPEN: 'Clique para abrir',
    CLOSE: 'Fechar',
    CLOSE_CURRENT_TAB: 'Fechar a aba atual',
    COLLAPSE_ALL: 'Fechar todos',
    CREATE_NEW_TAB: 'Criar nova aba',
    CURRENT_DIRECTORY: 'Pasta atual',
    CWD: 'CWD',
    DEBUG: 'Debug',
    DEBUGGER_CLEAR_CONSOLE: 'Limpar o console',
    DEBUGGER_CONNECTED: 'Debugger: conectado.',
    DEBUGGER_CONNECT_STATUS: 'Status de conexão',
    DEBUGGER_CONSOLE: 'Console',
    DEBUGGER_CONTINUE: 'Continuar',
    DEBUGGER_CONTINUE_ACTIVE_RUNNER: 'Debugger - continuar (executor ativo)',
    DEBUGGER_FIRST_BREAK: 'Debugger: conectado. Por favor crie um ponto de parada e clique no botão "Continuar" no painel do executor.',
    DEBUGGER_HELP: 'Ajuda',
    DEBUGGER_JUMP_TO_BREAK: 'Ir para o ponto de parada',
    DEBUGGER_LOOKUP_DEPTH: 'Profundidade de busca do Debugger',
    DEBUGGER_SCRIPTS: 'Scripts',
    DEBUGGER_STEP_IN: 'Passo para dentro',
    DEBUGGER_STEP_OUT: 'Passo para fora',
    DEBUGGER_STEP_OVER_ACTIVE_RUNNER: 'Debugger - passar por cima (executor ativo)',
    DEBUGGER_STEP_OVER_TO_NEXT_FUNCTION: 'Passar por cima para a próxima função',
    DEBUG_ACTIVE_RUNNER: 'Debug (executor ativo)',
    DIFF_ACTUAL: 'Atual',
    DIFF_EXPECTED: 'Esperado',
    DIFF_TITLE: 'Diferença Atual/Esperado',
    DIRECTORY: 'Pasta',
    EXPAND_ALL: 'Expandir todos',
    FILE: 'Arquivo',
    FLAGS_FOR_V8: 'Flags para v8',
    FLAGS_FOR_V8_PLACEHOLDER: 'exemplo: --use_strict --harmony',
    GLOBAL_ADDITIONAL_FLAGS: 'Flags Globais Adicionais',
    GLOBAL_ADDITIONAL_FLAGS_PLACEHOLDER: 'ex. --bail para o mocha, --require para o node',
    HIDE_DIFFERENCE: 'Esconder a diferença',
    INSTALL_DEPENDENCIES: 'Instalar dependências...',
    INSTALLATION_FAILED: 'Instalação falhou',
    INSTALLATION_FAILED_MESSAGE: 'A instalação não concluiu. Por favor vá até a pasta de extensões através do terminal e rode o comando "npm install".',
    INSTALLATION_FINISHED: 'Instalação concluída',
    JUMP_TO_REQUIRE: 'Ir para Require',
    NAME: 'Nome',
    NEW_TAB: 'Nova aba',
    OPEN_SETTINGS: 'Abrir configurações',
    PACKAGE: 'Pacote',
    PARENT_DIRECTORY: 'Pasta anterior',
    PATH_TO_MOCHA_BINARY: 'Caminho para o binário Mocha',
    PATH_TO_MOCHA_BINARY_PLACEHOLDER: 'deixe vazio para o comando global mocha',
    PATH_TO_NODE_BINARY: 'Caminho para o binário Node',
    PATH_TO_NODE_BINARY_PLACEHOLDER: 'deixe vazio para o comando global node',
    PATH_TO_NPM_BINARY: 'Caminho para o binário npm',
    PATH_TO_NPM_BINARY_PLACEHOLDER: 'deixe vazio para o comando global npm',
    REMOVE_BREAKPOINTS_ON_DISCONNECT: 'Remover os pontos de parada na desconexão',
    RINNERS_LIMITATION: 'Limitações: Você só pode inicializar 5 executores.',
    RUN: 'Executor',
    RUNNER_SETTINGS: 'Configurações do executor',
    SAVE: 'Gravar',
    SEARCH: 'Procurar',
    SETTINGS: 'Configurações...',
    SHOW_OR_HIDE_RUNNER: 'Mostrar/Esconder o executor',
    SHOW_DIFFERENCE: 'Mostrar diferença',
    START_ACTIVE_RUNNER: 'Iniciar (executor ativo)',
    START_CURRENT_MOCHA_FILE: 'Iniciar (Arquivo Mocha atual)',
    START_CURRENT_NODEJS_FILE: 'Iniciar (Arquivo NodeJS atual)',
    START_CURRENT_NODEJS_PROJECT: 'Iniciar (Projeto Mocha atual)',
    STOP: 'Parar',
    STOP_ACTIVE_RUNNER: 'Parar (executor ativo)',
    TARGET: 'Alvo',
    TARGET_EMPTY: 'O alvo na sua configuração de execução está vazio.',
    TESTS: 'Testes',
    TOGGLE_DEBUGGER: 'Alternar estado do debugger',
    TOGGLE_MOCHA: 'Alternar a visualização mocha'
});
